# Generated by Django 2.0.6 on 2019-05-09 17:35

import blog.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[(blog.constants.TestType('close'), blog.constants.TestType('close')), (blog.constants.TestType('open'), blog.constants.TestType('open'))], default=blog.constants.TestType('close'), max_length=128)),
                ('close_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Question')),
                ('open_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.OpenQuestion')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='blog.StoreQuestion'),
        ),
    ]
