# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='news_description',
            field=models.TextField(default=''),
        ),
    ]
