# Generated by Django 2.0.6 on 2019-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190509_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('passed', 'passed'), ('not passed', 'not passed'), ('pending', 'pending')], default='pending', max_length=128),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='status',
            field=models.CharField(choices=[('passed', 'passed'), ('not passed', 'not passed'), ('pending', 'pending')], default='pending', max_length=128),
        ),
    ]
